apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: dennis-nats
  namespace: prod
spec:
  size: 3
  version: "1.4.1"
  pod:
    enableConfigReload: true
    enableMetrics: true
    metricsImage: "synadia/prometheus-nats-exporter"
    metricsImageTag: "0.6.2"
  auth:
    enableServiceAccounts: true