apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-gateway
  namespace: prod 

  # Specifies which NATS cluster will be mapping this account.
  labels:
    nats_cluster: dennis-nats
spec:
  permissions:
    publish: ["build_book", "_INBOX.>"]
    subscribe: ["_INBOX.>"]
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-k8s-handler
  namespace: prod

  # Specifies which NATS cluster will be mapping this account.
  labels:
    nats_cluster: dennis-nats
spec:
  permissions:
    publish: ["create_book", "_INBOX.>"]
    subscribe: ["build_book","_INBOX.>"]
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-persistence-handler
  namespace: prod

  # Specifies which NATS cluster will be mapping this account.
  labels:
    nats_cluster: dennis-nats
spec:
  permissions:
    publish: ["_INBOX.>"]
    subscribe: ["create_book","_INBOX.>"]