apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-gateway
  namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-k8s-handler
  namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-persistence-handler
  namespace: prod
---